### ISSUE TITLE
License and distribution

### ISSUE THREAD

**Issue by michel-kraemer** [spartango/SuperS3t#9]
I've tested the official AWS Java client under Vert.x but the underlying Apache HttpClient isn't really scalable. So I'm looking for an alternative. SuperS3t looks really promising! :+1: 

I wonder under what license it is distributed. Would you mind adding a LICENSE file to the repository?

In addition, I suggest to publish SuperS3t to Maven Central so that people can easily use it. I can help you with this if you like (I've done it a couple of times for different open source libraries).

Cheers,
Michel

**Comment by spartango** [comment]
I've put a license in (should have done that ages ago), but frankly don't have the bandwidth to figure out the best way to put this up on Maven Central. If you have some quick guidance, however, I'd love to hear it!

**Comment by michel-kraemer** [comment]
Thanks for the LICENSE file!

First you should follow the OSSRH guide [1] to get the permission to upload to Maven central (if you haven't done so already). It's very simple and only takes a couple of minutes. You should get a response within a work day or so. Let me know when you're ready. I can then send you a pull request with the required changes to the `build.gradle` file.

Cheers,
Michel

[1] http://central.sonatype.org/pages/ossrh-guide.html

**Comment by spartango** [comment]
I'm going to need to change the package paths before I can go through with this, as I no longer own perceptus.com.

Annoyingly, this forces all users to make adjustments as well, so I might hold off for some time.

**Comment by ksclarke** [comment]
On the other hand, the longer you wait the more users you might have who will then have to adjust. :-)

**Comment by memoryhole** [comment]
Agreed with @ksclarke I just discovered this package today and will start using it. Having it published to Maven Central would be greatly convenient.

**Comment by spartango** [comment]
Ok, I'll start making the requisite changes to package naming in a branch and try to make the transition as painless as possible!
